runtime: go111

handlers:
- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon\.ico
- url: /robots\.txt
  static_files: assets/robots.txt
  upload: assets/robots\.txt
- url: /assets
  static_dir: assets
- url: /.*
  script: auto
